// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR7_0M4NMaRstVnYSW1ogQV17vI9rPO4',
    appId: '1:448080425337:web:b772b05cbe592ad79bffa8',
    messagingSenderId: '448080425337',
    projectId: 'security-app-1fd9b',
    authDomain: 'security-app-1fd9b.firebaseapp.com',
    storageBucket: 'security-app-1fd9b.appspot.com',
    measurementId: 'G-WJ0T8TTEX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYi6YmyycrRFbE-jeBgI8cG3uazHzuO5Q',
    appId: '1:448080425337:android:0ec377fead2415a09bffa8',
    messagingSenderId: '448080425337',
    projectId: 'security-app-1fd9b',
    storageBucket: 'security-app-1fd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKfFbfrnfUDxBmucxt3bJWSR3gQXeTLo',
    appId: '1:448080425337:ios:d90fa6a2eef8f5cd9bffa8',
    messagingSenderId: '448080425337',
    projectId: 'security-app-1fd9b',
    storageBucket: 'security-app-1fd9b.appspot.com',
    iosBundleId: 'com.example.securityAssessmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKfFbfrnfUDxBmucxt3bJWSR3gQXeTLo',
    appId: '1:448080425337:ios:d90fa6a2eef8f5cd9bffa8',
    messagingSenderId: '448080425337',
    projectId: 'security-app-1fd9b',
    storageBucket: 'security-app-1fd9b.appspot.com',
    iosBundleId: 'com.example.securityAssessmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsR7_0M4NMaRstVnYSW1ogQV17vI9rPO4',
    appId: '1:448080425337:web:5e3917b5f74562609bffa8',
    messagingSenderId: '448080425337',
    projectId: 'security-app-1fd9b',
    authDomain: 'security-app-1fd9b.firebaseapp.com',
    storageBucket: 'security-app-1fd9b.appspot.com',
    measurementId: 'G-N3FJ9JRG05',
  );
}
